### ISSUE TITLE
Use DrahtBot table as input

### ISSUE THREAD

**Issue by stickies-v** [achow101/ackboard#4]
Refreshing the PRs currently takes quite a while, because we need to fetch all the open PRs and all their comments. 

Has there been any consideration for using the DrahtBot summary tables that are already present on most open PRs as input, instead of parsing all the data on every refresh? I think this would:
1. be a massive performance improvement, since we'd just need to load the 1 comment per PR
2. avoid having to maintain two codebases for interpreting different kinds of ACKs
3. benefits from the "ignore" button that DrahtBot offers users

I don't currently see any downsides (besides perhaps losing some redundancy)? Happy to work on that, just checking if I'm missing any glaring problems.

**Comment by aureleoules** [comment]
I think this is a good idea, just a note:

> be a massive performance improvement, since we'd just need to load the 1 comment per PR

It would still require loading the first page of comments to get the summary comment, and for older PRs maybe multiple pages because the summary comment was not automatically created at the top.

It would be even better if Drahtbot could store the ACK table in JSON format hidden in markdown comment in the summary comment so that it can get parsed easier.

**Comment by stickies-v** [comment]
> It would still require loading the first page of comments to get the summary comment, and for older PRs maybe multiple pages because the summary comment was not automatically created at the top.

We don't necessarily need to load any comments initially, just the PR summary could be enough. Then we can use e.g. this query to load all DrahtBot comments (ideally we can filter for open PRs or PR numbers, but I'm not sure that's currently possible?):

```
{
  user(login: "DrahtBot") {
    issueComments(first: 1, orderBy: {field: UPDATED_AT, direction: DESC}) {
      nodes {
        repository {
          nameWithOwner
        }
        issue {
          number
        }
        updatedAt
        body
      }
    }
  }
}
```

And then for subsequent refreshes, we can use the `updatedAt` field to only load DrahtBot updates (and fetch new PRs if we find a comment that belongs to an unknown PR).

> It would be even better if Drahtbot could store the ACK table in JSON format hidden in markdown comment in the summary comment so that it can get parsed easier.

Yeah, agreed. That would be nice. I think parsing the current format shouldn't be a huge hurdle, though? 

I'll start playing around with this next week.

**Comment by aureleoules** [comment]
> We don't necessarily need to load any comments initially, just the PR summary could be enough.

Ah great, I've never tried the graphql api.

> I'll start playing around with this next week.

Good luck! :running_man:

**Comment by achow101** [comment]
I'm not sure that this would be that much faster? It seems like most of the time is spent waiting for github to respond to the request, and if we're going to be requesting all of drahtbot's comments, that could still take a long time. Also I'd like this to work on other repos, including ones that Drahtbot doesn't comment in.

**Comment by stickies-v** [comment]
> if we're going to be requesting all of drahtbot's comments, that could still take a long time.

I experimented a bit with this, and without being able to pre-filter for comments on open PRs, it indeed doesn't look like a performance improvement. Fetching even just the comment IDs of the ~7000 DrahtBot comments takes longer than the current refresh process. Coupled with the fact that you want to keep this decoupled from DrahtBot, I'll close this.
